"""
Pydantic schemas that define the analysis JSON contract.

These models serve three purposes:
1. They are the single source of truth for the structure the LLM must return.
2. Their JSON schema is passed to the LLM (Ollama `format` / OpenAI structured
   outputs) so the model is *constrained* to emit valid JSON.
3. They validate the parsed response, replacing the old fragile string parsing.
"""
from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class NodeType(str, Enum):
    decision = "decision"
    chance = "chance"
    outcome = "outcome"


class Outcome(BaseModel):
    """A distinct high-level outcome of the strategic situation."""

    description: str = Field(..., description="Clear description of this outcome")
    probability: float = Field(
        ..., ge=0.0, le=1.0, description="Likelihood of this outcome (0.0-1.0)"
    )
    key_factors: List[str] = Field(
        default_factory=list, description="2-4 factors that drive this outcome"
    )
    recommendation: str = Field(
        ..., description="Specific actionable advice for this outcome"
    )


class TreeNode(BaseModel):
    """A node in the decision tree.

    - decision nodes: choices the actor controls (no probability)
    - chance nodes:   uncertain events (require a probability)
    - outcome nodes:  terminal leaves (require a numeric payoff)
    """

    id: str
    label: str
    type: NodeType = NodeType.outcome
    children: List[str] = Field(default_factory=list)
    probability: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Probability of reaching this node from its parent (chance branches / weighted outcomes)",
    )
    payoff: Optional[float] = Field(
        default=None,
        description="Utility/value at a terminal outcome node. Higher is better. May be negative.",
    )

    # Computed server-side by backward induction (not requested from the LLM).
    expected_value: Optional[float] = Field(default=None)
    certainty_equivalent: Optional[float] = Field(
        default=None,
        description="Guaranteed payoff worth the same as this node's gamble to a risk-averse decider; None when risk-neutral",
    )
    is_optimal: bool = Field(
        default=False, description="True if on the optimal (EV-maximizing) path"
    )


class MatrixCell(BaseModel):
    """One cell of a two-player normal-form payoff matrix."""

    row_strategy: str = Field(..., description="Row player's strategy for this cell")
    col_strategy: str = Field(..., description="Column player's strategy for this cell")
    row_payoff: float = Field(..., description="Payoff to the row player")
    col_payoff: float = Field(..., description="Payoff to the column player")


class PayoffMatrix(BaseModel):
    """A two-player normal-form (simultaneous) game representation.

    Only meaningful when `applicable` is true. The LLM decides whether the
    situation fits this shape; equilibria are computed server-side.
    """

    applicable: bool = Field(
        default=False,
        description="True only if the situation is a simultaneous game between two players choosing discrete strategies",
    )
    player_row: str = Field(default="", description="Name of the row player")
    player_col: str = Field(default="", description="Name of the column player")
    row_strategies: List[str] = Field(default_factory=list)
    col_strategies: List[str] = Field(default_factory=list)
    cells: List[MatrixCell] = Field(
        default_factory=list,
        description="One cell per (row_strategy, col_strategy) combination",
    )


class DominanceFinding(BaseModel):
    """A dominated strategy, computed server-side (never generated by the LLM).

    `dominated_by` always beats `strategy` for `player`: strictly (better against
    every opponent strategy) or weakly (never worse, better somewhere).
    """

    player: str = Field(..., description="'row' or 'col'")
    player_name: str = ""
    strategy: str = Field(..., description="The strategy that should not be played")
    dominated_by: str = Field(..., description="The strategy that beats it")
    kind: str = "strict"  # "strict" or "weak"
    description: str = ""


class ParetoCell(BaseModel):
    """A Pareto-efficient outcome: no other cell improves one player without
    hurting the other."""

    row_strategy: str
    col_strategy: str
    row_payoff: float
    col_payoff: float


class NashEquilibrium(BaseModel):
    """A Nash equilibrium, computed server-side (never generated by the LLM)."""

    kind: str = "pure"  # "pure" or "mixed"
    profile: str = ""  # human-readable, e.g. "Cooperate / Defect"
    row_strategy: Optional[str] = None
    col_strategy: Optional[str] = None
    row_payoff: Optional[float] = None
    col_payoff: Optional[float] = None
    # Mixed equilibria: probability weights over the players' strategies.
    row_mix: Optional[List[float]] = None
    col_mix: Optional[List[float]] = None
    description: str = ""


class Analysis(BaseModel):
    """The full analysis contract returned to the frontend."""

    stakeholders: List[str] = Field(default_factory=list)
    summary: str = ""
    outcomes: List[Outcome] = Field(default_factory=list)
    recommended_outcome: str = ""
    decision_tree: List[TreeNode] = Field(default_factory=list)
    payoff_matrix: Optional[PayoffMatrix] = None

    # Computed server-side.
    optimal_decision: Optional[str] = Field(
        default=None, description="Label of the EV-maximizing first decision"
    )
    optimal_expected_value: Optional[float] = Field(default=None)
    optimal_certainty_equivalent: Optional[float] = Field(
        default=None,
        description="Certainty equivalent of the recommended path; None when risk-neutral",
    )
    risk_aversion: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Risk appetite applied: 0 risk-neutral, >0 risk-averse, <0 risk-seeking",
    )
    nash_equilibria: List[NashEquilibrium] = Field(default_factory=list)
    dominated_strategies: List[DominanceFinding] = Field(default_factory=list)
    pareto_efficient: List[ParetoCell] = Field(default_factory=list)
    game_notes: List[str] = Field(
        default_factory=list,
        description="Computed observations about the game (e.g. the equilibrium is not Pareto efficient)",
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="Structural problems found and repaired in the model's output",
    )


def llm_schema() -> dict:
    """JSON schema handed to the LLM to constrain its output.

    We expose only the fields the model should generate (server-computed fields
    like expected_value / is_optimal are excluded so the model doesn't waste
    tokens guessing them).
    """
    schema = Analysis.model_json_schema()
    # Trim server-computed properties from the schema we send to the model.
    _strip = {
        "Analysis": {
            "optimal_decision", "optimal_expected_value",
            "optimal_certainty_equivalent", "risk_aversion", "nash_equilibria",
            "dominated_strategies", "pareto_efficient", "game_notes", "warnings",
        },
        "TreeNode": {"expected_value", "certainty_equivalent", "is_optimal"},
    }
    for defname, props in _strip.items():
        target = schema.get("$defs", {}).get(defname, schema) if defname != "Analysis" else schema
        for prop in props:
            target.get("properties", {}).pop(prop, None)
    return schema
